### ISSUE TITLE
Stripe Integration

### ISSUE THREAD

**Issue by snewcomer** [Brainsware/sealas#20]
Would Stripe payments be something you would consider?  I'd be happy to discuss/help build this functionality if it isn't already in the works or implemented!

https://github.com/code-corps/stripity_stripe

**Comment by DKhalil** [comment]
Hey Scott, yes, they are planned, and were in fact already planned for the original project, but this is still quite a bit early. Right now, I want to finish the auth part and then get started with the foundations of the frontend.

Then there's always the additional challenge of how to integrate that into a system that's opaque to the actual server.

**Comment by snewcomer** [comment]
Perfect.  Would love to contribute in any way I can!
